package pe.edu.upc.center.workstation.bookingManagement.interfaces.acl;

public interface BookingsContextFacade {
    /**
     * Create a new booking entry.
     *
     * @param freelancerId The ID of the freelancer performing the booking
     * @param spaceId The ID of the workspace being booked
     * @param bookingDate The date the booking request was made
     * @param startDate The start date of the booking
     * @param endDate The end date of the booking
     * @return The booking code generated by the system
     */
    String createBooking(Long freelancerId, Long spaceId, String bookingDate, String startDate, String endDate);

    /**
     * Fetch a booking code by its freelancer and space combination.
     *
     * @param freelancerId The freelancer ID
     * @param spaceId The space ID
     * @return The booking code if found, or null otherwise
     */
    Long fetchBookingCode(Long freelancerId, Long spaceId);
}
